name: "Build Java"

on:
  push
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build Java micro service"
    
    steps:
    
      - name: "Checkout the code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: "SemVer"
        id: semver
        uses: zwaldowski/semver-release-action@v3
        with:
          bump: "patch"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
         
      - name: "Setup Java"
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'
      
      - name: "Build project by Maven"
        run: mvn -ntp clean package
       
      - name: "Build Docker image"
        uses: docker/build-push-action@v4
        with:
          tags: ${{ github.repository }}:${{ steps.semver.outputs.version }}
          context: ${{ github.workspace }}
      
      
