name: "Build Java"

on:
  push
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: "Checkout the code"
        uses: actions/checkout@v3
      
      - name: "Setup Java"
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      
      - name: "Build project by Maven"
        run: mvn clean package
       
      
      
